name: memory benchmark(baseline-evtx)
on:
  workflow_dispatch:
    inputs:
      ref_type:
        description: 'Reference type (branch or tag)'
        required: true
        type: choice
        options:
        - branch
        - tag
      ref_name:
        description: 'Reference name (branch name or tag name)'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
          submodules: recursive
          fetch-depth: 0

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Create a directory for extraction
        run: mkdir -p evtx_files

      - name: Download all-evtx.tgz
        run: curl -L https://github.com/NextronSystems/evtx-baseline/releases/download/v0.8/all-evtx.tgz -o all-evtx.tgz

      - name: Extract the tgz file into the directory
        run: tar -xzvf all-evtx.tgz -C evtx_files 1>/dev/null

      - name: Run on dev branch(update-rules)
        run: |
          free -h
          cargo run --release -- update-rules -q 1>/dev/null

      - name: Run on dev branch(json-timeline)
        run: |
          cargo run --release -- json-timeline -d ./evtx_files -C -o timeline.jsonl -L -p super-verbose -q -w -D -n -u --debug

      - name: Run on main branch(update-rules)
        run: |
          free -h
          git checkout main
          cargo run --release -- update-rules -q 1>/dev/null

      - name: Run on main branch(json-timeline)
        run: |
          cargo run --release -- json-timeline -d ./evtx_files -C -o timeline.jsonl -L -p super-verbose -q -w -D -n -u --debug
