name: memory benchmark(baseline-evtx)
on:
  workflow_dispatch:
    inputs:
      branch1:
        description: 'First branch to run benchmarks on'
        required: true
        default: 'main'
      branch2:
        description: 'Second branch to run benchmarks on'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Create a directory for extraction
        run: mkdir -p evtx_files

      - name: Download all-evtx.tgz
        run: curl -L https://github.com/NextronSystems/evtx-baseline/releases/download/v0.8/all-evtx.tgz -o all-evtx.tgz

      - name: Extract the tgz file into the directory
        run: tar -xzvf all-evtx.tgz -C evtx_files

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH1 }}
          submodules: recursive
          fetch-depth: 0

      - name: Run on dev branch(update-rules)
        run: |
          free -h
          cargo run --release -- update-rules -q

      - name: Run on dev branch(json-timeline)
        run: |
          cargo run --release -- json-timeline -d ./hayabusa-sample-evtx -o dev.jsonl -L -p super-verbose -q -w -D -n -u --debug

      - name: Checkout branch2
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH2 }}

      - name: Run on main branch(update-rules)
        run: |
          free -h
          cargo run --release -- update-rules -q

      - name: Run on main branch(json-timeline)
        run: |
          cargo run --release -- json-timeline -d ./hayabusa-sample-evtx -o main.jsonl -L -p super-verbose -q -w -D -n -u --debug
